'use strict';

angular.module('martaioApp').service('Marta', function ($http) {
  var marta = {};
  marta.arrivals = [];
  marta.arrivalGet = $http.get('/api/arrivals').then(function(data) {
    marta.arrivals = data;
  });
  marta.stations = ["AIRPORT STATION", "ARTS CENTER STATION", "ASHBY STATION", "AVONDALE STATION", "BANKHEAD STATION", "BROOKHAVEN STATION", "BUCKHEAD STATION", "CHAMBLEE STATION", "CIVIC CENTER STATION", "COLLEGE PARK STATION", "DECATUR STATION", "DORAVILLE STATION", "DUNWOODY STATION", "EAST LAKE STATION", "EAST POINT STATION", "EDGEWOOD CANDLER PARK STATION", "FIVE POINTS STATION", "GARNETT STATION", "GEORGIA STATE STATION", "INDIAN CREEK STATION", "INMAN PARK STATION", "KENSINGTON STATION", "KING MEMORIAL STATION", "LAKEWOOD STATION", "LENOX STATION", "LINDBERGH STATION", "MEDICAL CENTER STATION", "MIDTOWN STATION", "NORTH AVE STATION", "NORTH SPRINGS STATION", "OAKLAND CITY STATION", "OMNI DOME STATION", "PEACHTREE CENTER STATION", "SANDY SPRINGS STATION", "VINE CITY STATION", "WEST END STATION"];
  return marta;
});
